# Generated by Django 4.2.13 on 2024-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0002_product_settings_company_companylogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('Rp', 'Rupiah'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
