# Generated by Django 4.2.13 on 2024-07-01 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0004_remove_invoice_datecreated_remove_invoice_lastupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invoice',
            new_name='Invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('14 days', '14 Days'), ('30 days', '30 Days'), ('60 days', '60 Days')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('OVERDUE', 'OVERDUE'), ('PAID', 'PAID')], default='CURRENT', max_length=100),
        ),
    ]
