# Generated by Django 4.2.13 on 2024-07-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halo', '0005_rename_invoice_product_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
